#ifndef BATTERY_CONFIG_H
#define BATTERY_CONFIG_H

#define BATTERY_BRAND "Jinmasi"
#define BATTERY_MODEL "653042"
#define BATTERY_CAPACITY_MAH 700
#define BATTERY_ENERGY_WH 2.59f
#define BATTERY_NOMINAL_MV 3700

#define BATTERY_CHARGE_VOLTAGE_MV 4200
#define BATTERY_CHARGE_CURRENT_MA 350
#define BATTERY_INPUT_LIMIT_MA 500
#define BATTERY_CHARGE_ENABLE 1

#endif
